# NumPy
NumPy memiliki banyak fungsi dan kemampuan bawaan. Kami tidak akan membahas semuanya tetapi kami akan fokus pada beberapa aspek terpenting NumPy: vektor, array, matriks, dan pembuatan angka. Mari kita mulai dengan membahas array.

# NumPy Array

NumPy array adalah cara utama kita akan menggunakan NumPy selama kursus. NumPy array biasanya dipakai untuk menyelesaikan dua masalah: vektor dan matriks. Vektor benar-benar array 1 dimensi (1D) dan matriks adalah 2D (tetapi Anda harus mencatat bahwa matriks masih dapat memiliki hanya satu baris atau satu kolom).

## Mengapa menggunakan Numpy? Kenapa tidak list saja?

Ada banyak alasan untuk menggunakan Numpy dibandingkan list pada python. Alasan utama adalah:
* Efisiensi Memori Numpy Array vs list
* Mudah diperluas ke objek N-dimensi
* Kecepatan perhitungan array numpy
* Operasi dan fungsi dengan numpy
* Semua pustaka/library data science dan machine learning yang digunakan dibuat dengan Numpy

## Import NumPy

In [5]:
import numpy as np

## Membuat NumPy Array

In [6]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [47]:
type(my_list)

list

In [51]:
a1 = np.array(my_list)
a1

array([1, 2, 3])

In [52]:
type(a1)

numpy.ndarray

In [53]:
a1.shape

(3,)

In [54]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [55]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [56]:
type(a2), a2.shape

(numpy.ndarray, (2, 3))

In [57]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [64]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

## Built-in Methods NumPy array

### arange

Mengembalikan nilai dengan jarak yang sama dalam interval tertentu [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros dan ones

Hasilkan array nol atau satu. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 
Mengembalikan angka dengan jarak yang sama selama interval yang ditentukan [[reference](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

### eye

Membuat matriks identitas [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 
Numpy juga memiliki banyak cara untuk membuat susunan angka acak:

### rand
Membuat array dari bentuk yang diberikan dan mengisinya dengan sampel acak dari distribusi yang seragam ``[0, 1)``. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [21]:
np.random.rand(2)

array([0.53072575, 0.01283588])

In [22]:
np.random.rand(5,5)

array([[0.57688825, 0.24368392, 0.11297942, 0.26292978, 0.04533508],
       [0.37266243, 0.61698895, 0.24290489, 0.10654619, 0.20686208],
       [0.72768628, 0.30069309, 0.94681289, 0.31428431, 0.59528882],
       [0.33848884, 0.35154669, 0.15185327, 0.34968412, 0.10839434],
       [0.46337051, 0.06528307, 0.9415279 , 0.8966058 , 0.77565444]])

### randint
Mengembalikan bilangan bulat acak dari `rendah` (inklusif) ke `tinggi` (eksklusif).  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [25]:
np.random.randint(1,100)

98

In [26]:
np.random.randint(1,100,10)

array([92, 13, 39, 75, 53, 21, 11, 34, 52, 69])

### seed
Dapat digunakan untuk menyetel status acak, sehingga hasil "acak" yang sama dapat direproduksi ulang dan tetap dalam nominal yang sama. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [27]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [28]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Metode dan attribut pada array


In [61]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [63]:
ranarr

array([43, 24, 48, 26, 41, 27, 15, 14, 46, 43])

## Reshape
Mengembalikan array yang berisi data yang sama dengan bentuk baru. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

Ini adalah metode yang berguna untuk menemukan nilai maks atau min. Atau untuk menemukan lokasi indeks mereka menggunakan argmin atau argmax

In [33]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [34]:
ranarr.max()

39

In [35]:
ranarr.argmax()

7

In [36]:
ranarr.min()

2

In [37]:
ranarr.argmin()

9

## Shape

Shape adalah atribut yang dimiliki array (bukan metode):  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [38]:
# Vector
arr.shape

(25,)

In [39]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [40]:
arr.reshape(1,25).shape

(1, 25)

In [41]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [42]:
arr.reshape(25,1).shape

(25, 1)

### dtype

Anda juga bisa mengambil tipe data dari objek dalam array: [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]


[[Apa itu tipe data?](https://belajarpython.com/tutorial/tipe-data-python/)]

In [43]:
arr.dtype

dtype('int32')

In [44]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')