# Pengindeksan dan Seleksi NumPy

Kita akan membahas bagaimana memilih elemen atau grup elemen dari sebuah array.

[[Apa itu indexing?](https://realpython.com/lessons/indexing-and-slicing/)]

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Mengambil element dengan braket

In [ ]:
arr[8]

8

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

## Mengganti element dalam array

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[0] = 20
arr

array([20,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[0:5]=100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
slice_of_arr[:]=99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Index array 2D (matrix)

In [ ]:
arr_2d = np.array(([5,10,15],
                   [20,25,30],
                   [35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
arr[0]

1

In [ ]:
arr_2d[1]

array([20, 25, 30])

In [ ]:
# Formatnya adalah arr_2d[baris][kolom] atau arr_2d[baris,kolom]

arr_2d[1][0]

20

In [ ]:
arr_2d[1,0]

20

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# Slicing pada array 2D

arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr_2d[2]

array([35, 40, 45])

In [ ]:
arr_2d[2,-1]

45

## Visualisasi
![visualisasi](https://drive.google.com/uc?export=view&id=1nt8DMfLLgyW5LElrR6JRag-WsMEyxTH1)
<br>Image source: http://www.scipy-lectures.org/intro/numpy/numpy.html

## Pengkondisian

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])