# Operasi Pada Numpy

In [ ]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# warning nan
arr/arr

C:\Users\yogafatwanto\AppData\Local\Temp\ipykernel_18416\1334431799.py:2: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/arr

C:\Users\yogafatwanto\AppData\Local\Temp\ipykernel_18416\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

NumPy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, which are essentially just mathematical operations that can be applied across the array.<br>Let's show some common ones:

In [ ]:
# akar
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
# exponensial (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

C:\Anaconda3\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Ringkasan Statistik pada Array

NumPy juga menawarkan statistik ringkasan umum seperti <em>sum</em>, <em>mean</em> dan <em>max</em>.

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.sum()

45

In [ ]:
arr.mean()

4.5

In [ ]:
arr.max()

9

<strong>Other summary statistics include:</strong>
<pre>
arr.min() returns 0                   minimum
arr.var() returns 8.25                variance
arr.std() returns 2.8722813232690143  standard deviation
</pre>

## Logika Sumbu/Axis
Saat bekerja dengan array 2 dimensi (matriks), kita harus mempertimbangkan baris dan kolom. Ini menjadi sangat penting ketika kita masuk ke bagian tentang pandas. Dalam istilah array, sumbu 0 (nol) adalah sumbu vertikal (baris), dan sumbu 1 adalah sumbu horizontal (kolom). Nilai ini (0,1) sesuai dengan urutan pengembalian nilai <tt>arr.shape</tt>.

Mari kita lihat bagaimana hal ini memengaruhi kalkulasi statistik ringkasan kami dari atas.

In [ ]:
arr_2d = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

Dengan memasukkan <tt>axis=0</tt>, kita mengembalikan nilai penjumlahan sepanjang sumbu vertikal, pada dasarnya <tt>[(1+5+9), (2+6+10), (3 +7+11), (4+8+12)]</tt>

![visualisasi](https://drive.google.com/uc?export=view&id=1xoha2iF_8tqC1E5lZlo4rz50BCkHUX7M)

In [ ]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr_2d.sum(axis=1)

array([10, 26, 42])